name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t03-01-01
      id: t03-01-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-01-01
        setup-command: make compile
        command: make -s test_01
        input: |
          course-add#12S2203#Object-oriented Programming#3#C
          course-add#10S1002#Pemrograman Prosedural#2#D
          student-add#12S20999#Wiro Sableng#2020#Information Systems
          enrollment-add#12S2203#12S20999#2021/2022#even
          student-add#12S20111#Jaka Sembung#2019#Information Systems
          enrollment-add#12S2203#12S20111#2020/2021#even
          ---
        expected-output: |
          10S1002|Pemrograman Prosedural|2|D
          12S2203|Object-oriented Programming|3|C
          12S20999|Wiro Sableng|2020|Information Systems
          12S20111|Jaka Sembung|2019|Information Systems
          12S2203|12S20999|2021/2022|even|None
          12S2203|12S20111|2020/2021|even|None
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t03-01-02
      id: t03-01-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-01-02
        setup-command: make compile
        command: make -s test_01
        input: |
          course-add#MAS1101#Matematika Dasar I#4#D
          student-add#12S19010#Gabriel Indra Baringbing#2019#Information Systems
          course-add#FIS1103#Fisika Dasar#4#D
          course-add#TIS1101#Inovasi Digital#2#D
          course-add#12S1101#Dasar Sistem Informasi#3#D
          course-add#12S1102#Pemrograman Visual#2#D
          course-add#MAS1201#Matematika Dasar II#4#D
          course-add#KUS1001#Penulisan Karya Ilmiah#2#D
          course-add#KUS1201#Bahasa Inggris II#2#D
          course-add#KUS1202#Pengantar Rekayasa dan Desain#2#D
          course-add#10S1001#Matematika Diskret#3#D
          student-add#12S19030#Jaime Christ Bonar Sirait#2019#Information Systems
          student-add#12S19036#Lucas Ronaldi Hutabarat#2019#Information Systems
          student-add#12S19038#Pabertoni Panjaitan#2019#Information Systems
          course-add#10S1002#Pemrograman Prosedural#2#D
          course-add#10S2001#Arsitektur dan Organisasi Komputer#3#D
          course-add#MAS2001#Probabilitas dan Statistika#3#C
          course-add#KUS2001#Bahasa Inggris III#2#C
          course-add#10S2101#Algoritma dan Struktur Data#3#C
          course-add#11S1213#Rekayasa Perangkat Lunak#3#C
          course-add#12S2101#Organisasi dan Manajemen#3#C
          course-add#12S2102#Basis Data#4#C
          course-add#10S2201#Aljabar Linier#3#C
          course-add#10S2202#Jaringan Komputer#3#C
          course-add#10S2203#Sistem Operasi#3#C
          course-add#12S2201#Analisis dan Desain Sistem#3#C
          course-add#12S2202#Interaksi Manusia-Komputer#3#C
          course-add#12S2203#Pemrograman Berorientasi Objek#3#C
          course-add#KUS4101#Pancasila dan Kewarganegaraan#2#C
          course-add#TIS3001#Keteknowiraan#3#C
          course-add#10S3001#Kecerdasan Buatan#4#C
          course-add#12S3101#Pemrograman dan Pengujian Aplikasi Web#4#C
          course-add#12S3102#Basis Data Lanjut#3#C
          course-add#12S3103#Manajemen Proyek Sistem Informasi#3#C
          course-add#KUS3001#Analisis Dampak Lingkungan#2#C
          course-add#KUS3002#Agama dan Etika#2#C
          course-add#12S3201#Perencanaan Sumber Daya Perusahaan#4#C
          course-add#12S3202#Gudang Data dan Kecerdasan Bisnis#3#C
          course-add#12S3203#Proyek Sistem Informasi#4#C
          course-add#12S3204#Keamanan Sistem#3#C
          course-add#12S4001#Tugas Akhir I#4#BC
          course-add#12S4003#Kerja Praktik#3#C
          course-add#12S4002#Tugas Akhir II#4#BC
          course-add#12S4004#Sertifikasi Profesi#3#C
          course-add#12S4005#Hukum dan Etika Siber#2#C
          course-add#12S4006#Kapita Selekta#2#C
          student-add#12S19003#Dian Filia Matondang#2019#Information Systems
          student-add#12S19005#Amelia Jane Audri Lumbanraja#2019#Information Systems
          student-add#12S19015#Putri Anyelir BR Tobing#2019#Information Systems
          student-add#12S19025#Petrus Aquanur Sinaga#2019#Information Systems
          student-add#12S19027#Gilbert E M Hutajulu#2019#Information Systems
          student-add#12S19044#Elisabet Margaret Sirait#2019#Information Systems
          course-add#KUS1101#Bahasa Inggris I#2#D
          course-add#KUS1102#Pembentukan Karakter Del#2#D
          student-add#12S19055#Dwita Sihombing#2019#Information Systems
          student-add#12S19062#Ardika Solagratia Sianturi#2019#Information Systems
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          student-add#12S20003#Marcel Joshua Parulian Simanjuntak#2020#Information Systems
          student-add#12S20005#Juan Evander Klose Sitompul#2020#Information Systems
          student-add#12S20006#Nadya  Dioranta Tambunan#2020#Information Systems
          student-add#12S20007#Rufina Aprilina Sitorus#2020#Information Systems
          student-add#12S20008#Putri Rachel Geby Tampubolon#2020#Information Systems
          student-add#12S20009#Agnes Marpaung#2020#Information Systems
          student-add#12S20010#Suprianto Dharma Sitompul#2020#Information Systems
          student-add#12S20011#Gabriel Saputra Panggabean#2020#Information Systems
          student-add#12S20012#Ary Gunawan Raja Dirumana Aritonang#2020#Information Systems
          student-add#12S20013#Lydia Tesalonika#2020#Information Systems
          student-add#12S20014#Lidia Ginting#2020#Information Systems
          student-add#12S20015#Niver Titi Sibuea#2020#Information Systems
          student-add#12S20016#Via Uni Rosa Sianipar#2020#Information Systems
          student-add#12S20017#Lile Asima Manalu#2020#Information Systems
          student-add#12S20018#Gabriella Putri Panjaitan#2020#Information Systems
          student-add#12S20019#Kristina Margaret Sitorus#2020#Information Systems
          student-add#12S20020#Wahyu Krisdangolyanti Simamora#2020#Information Systems
          student-add#12S20021#Sintia Lolita Silaen#2020#Information Systems
          student-add#12S20022#Agnes Veronika Sihombing#2020#Information Systems
          student-add#12S20023#Mares. G.H. Siagian#2020#Information Systems
          student-add#12S20024#Sandro Sinaga#2020#Information Systems
          student-add#12S20025#Irma Naomi Irene Tampubolon#2020#Information Systems
          student-add#12S20026#Mastuari Octafiana Sirumapea#2020#Information Systems
          student-add#12S20029#Yehezchiel Abed Rafles Sibuea#2020#Information Systems
          student-add#12S20030#Lamsihar Siahaan#2020#Information Systems
          student-add#12S20031#Daniel Andres Simangunsong#2020#Information Systems
          student-add#12S20032#Permana Gabriel Panjaitan#2020#Information Systems
          student-add#12S20034#Daniel Paskah Totti Limbong#2020#Information Systems
          student-add#12S20035#Nemnem Sihombing#2020#Information Systems
          student-add#12S20036#Winda Sari Butar Butar#2020#Information Systems
          student-add#12S20037#Angelita Dumaria Panjaitan#2020#Information Systems
          student-add#12S20038#Arni Febryarti Sitorus#2020#Information Systems
          student-add#12S20040#Esphi Aphelina Hutabarat#2020#Information Systems
          student-add#12S20041#Theresia Agatha Silas Siahaan#2020#Information Systems
          student-add#12S20042#Mastawila Febryanti Simanjuntak#2020#Information Systems
          student-add#12S20043#Sevia Rajagukguk#2020#Information Systems
          student-add#12S20044#Hanna Dhea Christi Sihombing#2020#Information Systems
          student-add#12S20045#Christine Hutagaol#2020#Information Systems
          student-add#12S20046#Patricia Dian Margaretha S#2020#Information Systems
          student-add#12S20047#Ruth Christine Manurung#2020#Information Systems
          student-add#12S20048#Jevania#2020#Information Systems
          student-add#12S20049#Meida Enggelica Butarbutar#2020#Information Systems
          student-add#12S20050#Putri Esrahana Manurung#2020#Information Systems
          student-add#12S20051#Rony Samuel Sinaga#2020#Information Systems
          student-add#12S20052#Eka Rohani Gultom#2020#Information Systems
          student-add#12S20053#Andri Anjelia Hutapea#2020#Information Systems
          student-add#12S20054#Rossianna Dewi Sri Hutabarat#2020#Information Systems
          student-add#12S20055#Aygrace Lia Hutagaol#2020#Information Systems
          student-add#12S20056#Siska Romaito Manullang#2020#Information Systems
          enrollment-add#12S3102#12S20047#2020/2021#odd
          enrollment-add#12S4003#12S20023#2020/2021#even
          enrollment-add#KUS4101#12S20021#2020/2021#odd
          enrollment-add#12S3103#12S20050#2021/2022#odd
          enrollment-add#12S3102#12S20034#2020/2021#odd
          enrollment-add#FIS1103#12S20010#2021/2022#odd
          enrollment-add#12S2202#12S20012#2021/2022#odd
          enrollment-add#12S1102#12S20050#2021/2022#odd
          enrollment-add#12S3101#12S20022#2021/2022#odd
          enrollment-add#KUS4101#12S20053#2020/2021#odd
          ---
        expected-output: |
          11S1213|Rekayasa Perangkat Lunak|3|C
          KUS1202|Pengantar Rekayasa dan Desain|2|D
          KUS1201|Bahasa Inggris II|2|D
          KUS1102|Pembentukan Karakter Del|2|D
          MAS2001|Probabilitas dan Statistika|3|C
          KUS3001|Analisis Dampak Lingkungan|2|C
          KUS1101|Bahasa Inggris I|2|D
          KUS1001|Penulisan Karya Ilmiah|2|D
          KUS3002|Agama dan Etika|2|C
          10S2101|Algoritma dan Struktur Data|3|C
          10S2001|Arsitektur dan Organisasi Komputer|3|D
          MAS1201|Matematika Dasar II|4|D
          10S2203|Sistem Operasi|3|C
          10S2202|Jaringan Komputer|3|C
          10S2201|Aljabar Linier|3|C
          12S3204|Keamanan Sistem|3|C
          FIS1103|Fisika Dasar|4|D
          12S3102|Basis Data Lanjut|3|C
          12S3201|Perencanaan Sumber Daya Perusahaan|4|C
          12S3101|Pemrograman dan Pengujian Aplikasi Web|4|C
          12S1101|Dasar Sistem Informasi|3|D
          12S3203|Proyek Sistem Informasi|4|C
          12S1102|Pemrograman Visual|2|D
          12S3103|Manajemen Proyek Sistem Informasi|3|C
          12S3202|Gudang Data dan Kecerdasan Bisnis|3|C
          12S4002|Tugas Akhir II|4|BC
          12S4001|Tugas Akhir I|4|BC
          MAS1101|Matematika Dasar I|4|D
          KUS2001|Bahasa Inggris III|2|C
          KUS4101|Pancasila dan Kewarganegaraan|2|C
          10S1001|Matematika Diskret|3|D
          10S3001|Kecerdasan Buatan|4|C
          10S1002|Pemrograman Prosedural|2|D
          12S2203|Pemrograman Berorientasi Objek|3|C
          TIS1101|Inovasi Digital|2|D
          12S4004|Sertifikasi Profesi|3|C
          12S2101|Organisasi dan Manajemen|3|C
          TIS3001|Keteknowiraan|3|C
          12S4003|Kerja Praktik|3|C
          12S2102|Basis Data|4|C
          12S2201|Analisis dan Desain Sistem|3|C
          12S4006|Kapita Selekta|2|C
          12S2202|Interaksi Manusia-Komputer|3|C
          12S4005|Hukum dan Etika Siber|2|C
          12S20025|Irma Naomi Irene Tampubolon|2020|Information Systems
          12S20026|Mastuari Octafiana Sirumapea|2020|Information Systems
          12S20023|Mares. G.H. Siagian|2020|Information Systems
          12S20024|Sandro Sinaga|2020|Information Systems
          12S20029|Yehezchiel Abed Rafles Sibuea|2020|Information Systems
          12S20032|Permana Gabriel Panjaitan|2020|Information Systems
          12S19044|Elisabet Margaret Sirait|2019|Information Systems
          12S20030|Lamsihar Siahaan|2020|Information Systems
          12S20031|Daniel Andres Simangunsong|2020|Information Systems
          12S19003|Dian Filia Matondang|2019|Information Systems
          12S19005|Amelia Jane Audri Lumbanraja|2019|Information Systems
          12S20036|Winda Sari Butar Butar|2020|Information Systems
          12S20037|Angelita Dumaria Panjaitan|2020|Information Systems
          12S20034|Daniel Paskah Totti Limbong|2020|Information Systems
          12S20035|Nemnem Sihombing|2020|Information Systems
          12S20038|Arni Febryarti Sitorus|2020|Information Systems
          12S20040|Esphi Aphelina Hutabarat|2020|Information Systems
          12S19010|Gabriel Indra Baringbing|2019|Information Systems
          12S20043|Sevia Rajagukguk|2020|Information Systems
          12S19055|Dwita Sihombing|2019|Information Systems
          12S20044|Hanna Dhea Christi Sihombing|2020|Information Systems
          12S20041|Theresia Agatha Silas Siahaan|2020|Information Systems
          12S20042|Mastawila Febryanti Simanjuntak|2020|Information Systems
          12S19015|Putri Anyelir BR Tobing|2019|Information Systems
          12S20009|Agnes Marpaung|2020|Information Systems
          12S20003|Marcel Joshua Parulian Simanjuntak|2020|Information Systems
          12S20047|Ruth Christine Manurung|2020|Information Systems
          12S20048|Jevania|2020|Information Systems
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20045|Christine Hutagaol|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S20046|Patricia Dian Margaretha S|2020|Information Systems
          12S20007|Rufina Aprilina Sitorus|2020|Information Systems
          12S20008|Putri Rachel Geby Tampubolon|2020|Information Systems
          12S20005|Juan Evander Klose Sitompul|2020|Information Systems
          12S20049|Meida Enggelica Butarbutar|2020|Information Systems
          12S20006|Nadya  Dioranta Tambunan|2020|Information Systems
          12S20050|Putri Esrahana Manurung|2020|Information Systems
          12S19062|Ardika Solagratia Sianturi|2019|Information Systems
          12S20051|Rony Samuel Sinaga|2020|Information Systems
          12S20010|Suprianto Dharma Sitompul|2020|Information Systems
          12S20054|Rossianna Dewi Sri Hutabarat|2020|Information Systems
          12S20011|Gabriel Saputra Panggabean|2020|Information Systems
          12S20055|Aygrace Lia Hutagaol|2020|Information Systems
          12S20052|Eka Rohani Gultom|2020|Information Systems
          12S20053|Andri Anjelia Hutapea|2020|Information Systems
          12S19025|Petrus Aquanur Sinaga|2019|Information Systems
          12S19027|Gilbert E M Hutajulu|2019|Information Systems
          12S20014|Lidia Ginting|2020|Information Systems
          12S20015|Niver Titi Sibuea|2020|Information Systems
          12S20012|Ary Gunawan Raja Dirumana Aritonang|2020|Information Systems
          12S20056|Siska Romaito Manullang|2020|Information Systems
          12S20013|Lydia Tesalonika|2020|Information Systems
          12S20018|Gabriella Putri Panjaitan|2020|Information Systems
          12S20019|Kristina Margaret Sitorus|2020|Information Systems
          12S20016|Via Uni Rosa Sianipar|2020|Information Systems
          12S20017|Lile Asima Manalu|2020|Information Systems
          12S19030|Jaime Christ Bonar Sirait|2019|Information Systems
          12S20021|Sintia Lolita Silaen|2020|Information Systems
          12S20022|Agnes Veronika Sihombing|2020|Information Systems
          12S20020|Wahyu Krisdangolyanti Simamora|2020|Information Systems
          12S19036|Lucas Ronaldi Hutabarat|2019|Information Systems
          12S19038|Pabertoni Panjaitan|2019|Information Systems
          12S3102|12S20047|2020/2021|odd|None
          KUS4101|12S20021|2020/2021|odd|None
          KUS4101|12S20053|2020/2021|odd|None
          12S3103|12S20050|2021/2022|odd|None
          12S3102|12S20034|2020/2021|odd|None
          12S2202|12S20012|2021/2022|odd|None
          12S4003|12S20023|2020/2021|even|None
          FIS1103|12S20010|2021/2022|odd|None
          12S3101|12S20022|2021/2022|odd|None
          12S1102|12S20050|2021/2022|odd|None
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t03-02-01
      id: t03-02-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-02-01
        setup-command: make compile
        command: make -s test_02
        input: |
          course-add#12S2203#Object-oriented Programming#3#C
          course-add#10S1002#Pemrograman Prosedural#2#D
          student-add#12S20999#Wiro Sableng#2020#Information Systems
          enrollment-add#12S2203#12S20999#2021/2022#even
          student-add#12S20111#Jaka Sembung#2019#Information Systems
          enrollment-add#12S2203#12S20000#2020/2021#even
          enrollment-add#12S2200#12S20000#2020/2021#odd
          ---
        expected-output: |
          invalid student|12S20000
          invalid course|12S2200
          10S1002|Pemrograman Prosedural|2|D
          12S2203|Object-oriented Programming|3|C
          12S20999|Wiro Sableng|2020|Information Systems
          12S20111|Jaka Sembung|2019|Information Systems
          12S2203|12S20999|2021/2022|even|None
        comparison-method: exact
        timeout: 1
        max-score: 15
    - name: t03-02-02
      id: t03-02-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-02-02
        setup-command: make compile
        command: make -s test_02
        input: |
          course-add#12S2203#Object-oriented Programming#3#C
          course-add#10S1002#Pemrograman Prosedural#2#D
          enrollment-add#12S2203#12S20999#2021/2022#even
          student-add#12S20999#Wiro Sableng#2020#Information Systems
          enrollment-add#12S2203#12S20999#2021/2022#even
          student-add#12S20111#Jaka Sembung#2019#Information Systems
          enrollment-add#12S2200#12S20000#2020/2021#odd
          ---
        expected-output: |
          invalid student|12S20999
          invalid course|12S2200
          10S1002|Pemrograman Prosedural|2|D
          12S2203|Object-oriented Programming|3|C
          12S20999|Wiro Sableng|2020|Information Systems
          12S20111|Jaka Sembung|2019|Information Systems
          12S2203|12S20999|2021/2022|even|None
        comparison-method: exact
        timeout: 1
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T03-01-01_RESULTS: "${{steps.t03-01-01.outputs.result}}"
        T03-01-02_RESULTS: "${{steps.t03-01-02.outputs.result}}"
        T03-02-01_RESULTS: "${{steps.t03-02-01.outputs.result}}"
        T03-02-02_RESULTS: "${{steps.t03-02-02.outputs.result}}"
      with:
        runners: t03-01-01,t03-01-02,t03-02-01,t03-02-02
